//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MehWebApplication.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gem
    {
        public Gem()
        {
            this.GemImages = new HashSet<GemImage>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rarity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Shine { get; set; }
        public string Color { get; set; }
        public Nullable<int> Faces { get; set; }
    
        public virtual ICollection<GemImage> GemImages { get; set; }
    }
}
