//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MehWebApplication.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NoobDBEntitiesNew : DbContext
    {
        public NoobDBEntitiesNew()
            : base("name=NoobDBEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GemImage> GemImages { get; set; }
        public virtual DbSet<Gem> Gems { get; set; }
        public virtual DbSet<GemsTable> GemsTables { get; set; }
        public virtual DbSet<test_View_1> test_View_1 { get; set; }
    }
}
